---
commitizen:
  bump_message: "bump(latex-git-log): version $current_version \u2192 $new_version"
  gpg_sign: true
  name: cz_conventional_commits
  tag_format: latex-git-log/v$version
  use_shortcuts: true
  version: 1.0.0
  version_files:
  - latex-git-log
  version_scheme: semver
